kind: PersistentVolume
apiVersion: v1
metadata:
  name: qod-pv-volume  # Sets PV's name
  labels:
    type: local  # Sets PV's type to local
    app: qod-db
spec:
  storageClassName: manual
  capacity:
    storage: 128Mi # Sets PV Volume
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/srv/mysql"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: qod-pv-claim  # Sets name of PVC
  labels:
    app: qod-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany  # Sets read and write access
  resources:
    requests:
      storage: 128Mi  # Sets volume size

