apiVersion: v1
kind: Service
metadata:
  name: qod-db
  labels:
    app: qod-db
    tier: data
spec:
  type: ClusterIP
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
      protocol: TCP 
  selector:
    app: qod-db

